### ISSUE TITLE
yarn run production consumes too much resource

### ISSUE THREAD

**Issue by Hao-Wu** [tuandm/laravue#104]
There is no problem running on local dev machine, of course.

However when I am trying to deploy onto cloud server, which is a 1 core cpu + 1 GB memory virtual host, the `yarn run production` is almost impossible to finish build job. The 1GB memory is totally consumed by the build process.

Is there any workaround to reduce the resource consumption. Maybe some optimization on webpack script will work.

**Comment by songyuchen88** [comment]
app.js and vendor.js are too big

**Comment by woodzeng** [comment]
> app.js and vendor.js are too big

me too, how to resolve it?

**Comment by tuandm** [comment]
@songyuchen88, @Hao-Wu 
Since Laravue is SPA, it contains all imported libraries which increase the bundle sizes. You can run `yarn run report` to see all dependencies and their size. You can also remove unused libraries to reduce the size. After minified and gzip, the bundles are not too big: 
![image](https://user-images.githubusercontent.com/490446/71866714-c23e9680-3139-11ea-8945-220229ea743a.png)

Please read here: https://doc.laravue.dev/guide/#analyze-the-build-file-size

**Comment by azulkipli** [comment]
> app.js and vendor.js are too big

you can try lazy load router
https://vueschool.io/articles/vuejs-tutorials/lazy-loading-and-code-splitting-in-vue-js/

analyze bundle size of course

**Comment by tuandm** [comment]
@Hao-Wu you can run webpack on your local machine then deploy the compiled assets to your server. We don't have plan to optimize webpack at this moment since Laravue uses many useful libraries, which brings more works to webpack.
