### ISSUE TITLE
Seems like it is not mobile friendly

### ISSUE THREAD

**Issue by maximousblk** [tuandm/laravue#112]
![Screenshot_20191218-000100_Chrome](https://user-images.githubusercontent.com/28438021/71024018-fe2d9f80-2129-11ea-8399-db8e045a6724.jpg)
![Screenshot_20191218-000217_Chrome](https://user-images.githubusercontent.com/28438021/71024040-0dace880-212a-11ea-9bc8-a554c276a80b.jpg)
Some parts break when on smartphones.

Sorry if this issue is not parallel to the CoC.

**Comment by tuandm** [comment]
@maximousblk Laravue is built on top of [ElementUI](https://element.eleme.io/#/en-US) which is a Desktop UI Library originally. Therefore, the responsive is the limitation and it doesn't get support from the vendor itself. We are trying to enhance as much as possible but it is not recommended using mobile to browse Laravue. At the end, Laravue is positioned for an enterprise administrator system and mobile layout is not on our top priorities.

**Comment by TheRealMattLear** [comment]
To be fair, tables aren't very mobile friendly to begin with. The drag table is likely never going to be mobile friendly because it relies on a click+drag of the entire row. A resolution for this would be to add an anchor point instead of click+drag the entire row. As for the profile page, that's not a difficult fix.
