### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by FerRubioMorales** [tuandm/laravue#14]
The first.... AWESOME PROJECT AND WORK!

Just a question, where can I find documentation? Will be helpfully for create new pages or components.

Thanks!

**Comment by tuandm** [comment]
@FerRubioMorales Thanks for reaching this project. I'm working on the documentation and will release it as soon as possible.

**Comment by FerRubioMorales** [comment]
Nice to know this 👌 just a question, how user session is managed? Do you use the laravel session? I made a controller in another web route and I always get null on auth::user but I’m logged in the vue page.

**Comment by tuandm** [comment]
@FerRubioMorales Since this is SPA, we don't use Laravel Session for API part - we are using [JWT-Auth](https://github.com/tymondesigns/jwt-auth). Please check /routes/api.php.

In other web controller, you have to write your own authentication guard.
Basically, we don't change anything of Laravel framework, just use api guard as default (please check /config/auth.php).

**Comment by tuandm** [comment]
@FerRubioMorales Please check the first document here: https://doc.laravue.dev
