### ISSUE TITLE
Will you add new feature？

### ISSUE THREAD

**Issue by legeng** [tuandm/laravue#25]
The project I have been looking for for a long time has finally appeared.
First of all, thank you very much for your contribution.

Especially users, role, permission  and routing，example use  the package of spatie/laravel-permission ? Because adding these is like a perfect system.I really hope that you can add these features.

**Comment by tuandm** [comment]
@legeng Thanks for reaching this project. Yes - laravel packages will be added to this project as separated modules after releasing the first stable version. We are working on the documentation and will release it soon as possible.

**Comment by legeng** [comment]
Thank you very much for your contribution, look forward to your stable version and documentation.

**Comment by tuandm** [comment]
@legeng spatie/laravel-permission has been added to new release of Laravue (0.5.0). Please check it out.

**Comment by legeng** [comment]
@tuandm Hello, thank you very much for making this feature, but I want to know if this piece is designed. What is the idea, if I want to add a role or menu, or permissions, what should I do. I hope that you have time to perfect this feature.

**Comment by tuandm** [comment]
@legeng Roles and permissions should be added by migrations because they need to appear in source code. After adding role/permission, we can assign permission to role or user from here: https://laravue.dev/#/administrator/roles and https://laravue.dev/#/administrator/users.

We are working on the documentation to provide a development guideline for this project, such as how to work with resource, menu, permission...

We are also working on CLI feature to allow generating menus via command line, many users asked for that.

Regards
