### ISSUE TITLE
Fetching data to build form

### ISSUE THREAD

**Issue by diegodcl** [tuandm/laravue#30]
First of all. Excelent Job!!!

I think my question will be covered in the docs. But I´ve been playing with laravue, I´d like to know wich is the best way to load data for selects to build a form. It´s not even a question directly related to laravue especifically, but I´d like your suggestion.

I found out, that the requests to the server api, are made from js files in the api folder. Do you think it would be better to make a js file to load all the information to use on the form, like form.js (loading select options, radio options all at once) ? The orther way would be creating related to the select itself like cities.js, to fill the cities select in the form? 

I´m newbie in vue. Hope I´ve explained well my question. Sorry if it´s not the right place to discuss this kind of thing. Really thankfull for your work.

**Comment by tuandm** [comment]
@diegodcl Thanks for reaching this project.
From the initialized design, we will use [vue-resource](https://github.com/pagekit/vue-resource) to bind with Laravel's resources. Then we will have some common js files to handle general APIs (like your `form.js`). Next release of Laravue will contain document and example code.

**Comment by diegodcl** [comment]
Thank you, for your answer. Could you give us a release date for the docs?

**Comment by tuandm** [comment]
@diegodcl To release, we have prepared more things - like sample api/crud/resource... and especially the documentation. You can check the [pre-release](https://github.com/tuandm/laravue/tree/feature/before-release) branch for new updates. 

The docs will be released this April :).

Regards

**Comment by tuandm** [comment]
@diegodcl Sorry for this late update.
Since Vue has dropped [vue-resource](https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4) so we have decided to implement [resource class](https://github.com/tuandm/laravue/blob/master/resources/js/api/resource.js) using axios. You can check example on [user module](https://github.com/tuandm/laravue/tree/master/resources/js/views/users). 

In Laravel side, just create Laravel Resource and API controller, quite simple.

Here is the demo: https://laravue.dev/#/administrator/users

**Comment by tuandm** [comment]
@diegodcl Please check the doc here: https://doc.laravue.dev
