### ISSUE TITLE
Why use JWT and not passport?

### ISSUE THREAD

**Issue by evecimar** [tuandm/laravue#54]
First of all I would like to congratulate you for the excellent work. I am studying it to put on a project person.

My question is regarding API authentication. I saw that you use "tymondesigns / jwt-auth". My question is why not use the laravel passport?

Sorry for my english, I'm using google translator.

**Comment by tuandm** [comment]
Hi @evecimar,
Thanks for reaching this project.
The main reason for using tymon/jwt-auth is because it's simple and easy to setup without adding new routes/tables/fields. jwt-auth is better in term of providing simple authentication and it's faster to deliver all the features we want to introduce in the first release.
Laravel passport is great, and would be suitable for real projects which will have more sub-systems than just a backend. We will consider adding Laravel passport to the roadmap.

**Comment by evecimar** [comment]
Tks

**Comment by tuandm** [comment]
@evecimar We would like to ask your approval to use your comment on our website as a testimonial? We may use your name, avatar and github url as the credit. Let me know if you have any concern.

Regards,
Tuan Duong

**Comment by evecimar** [comment]
Yes, you can.

**Comment by tuandm** [comment]
@evecimar FYI: Laravue starts using Laravel Passport from [version@0.9.0](https://github.com/tuandm/laravue/releases/tag/0.9.0)
