### ISSUE TITLE
Question - control premissions add - edit - delete

### ISSUE THREAD

**Issue by Momaiz** [tuandm/laravue#61]
Hello Bro ,
Thank you for perfect admin panel , it's really helpful .

i have question about roles and premissions please .

 Where can i control role or premissions add - edit - delete ??

**Comment by tuandm** [comment]
Hi @Momaiz,

As designed, permissions/roles will be added by migrations (direct in DB) because extra development should be involved (i.e update middlewares, controllers, routes...). 

Example: https://github.com/tuandm/laravue/blob/master/database/migrations/2019_04_20_130706_setup_role_permissions.php 

After new roles/permissions are in DB, you can manage them via UI: 
https://laravue.dev/#/administrator/roles
https://laravue.dev/#/administrator/users

**Comment by Momaiz** [comment]
Hi @tuandm ,
Thank you for answer .

Yes I noticed that .
In premission table 

`view menu "xxx"`  this will apper under **Menus**

`manage "xxx"` this apper under **Permissions**

Should I change it on `laravue/models/acl.php`

![image](https://user-images.githubusercontent.com/20012757/62456019-d3910a80-b777-11e9-9abc-da51b0d9f642.png)

Thank you

**Comment by tuandm** [comment]
@Momaiz 
You can change everything according to your business and requirements. Our code is to create a skeleton and for the simple demo :). If you think there is anything can be improved, feel free to create issues/PRs.
