### ISSUE TITLE
User Register and Login Page

### ISSUE THREAD

**Issue by MRUBS** [tuandm/laravue#66]
How can i create user registration and login page easily so that each new register use listed as user role only?

**Comment by tuandm** [comment]
@MRUBS This project is positioned for a backend system which offers user creation feature via [user management](https://laravue.dev/#/administrator/users). You have to write user registration in front-end page.

**Comment by MRUBS** [comment]
Yes, i get that. So, can i use the same user create method for registration a new user, same thing you did in the backend.

**Comment by tuandm** [comment]
@MRUBS Yes, something like that, you can use the current code as reference.
Please kindly note that current user routes require middleware `permission:manage user`:

```php
// File routes/api.php
Route::apiResource('users', 'UserController')->middleware('permission:' . \App\Laravue\Acl::PERMISSION_USER_MANAGE);
```
while your user registration feature should not require any permission (since it will only be used by non-logged in users), therefore it's recommended to create new API routes without middleware for this.

**Comment by MRUBS** [comment]
Got it, thanks.
